### ISSUE TITLE
[PE-D][Tester C] Deleting an item does not delete it from the customer's orders

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T13-4/tp#123]
Steps to reproduce:
1. Run the following command: `addorder n/David Li i/Chocolate Croissant`
2. Run the following command: `delitem i/Chocolate Croissant`

Expected behaviour: maybe to show that the item has been discontinued in the user's view.

Actual behaviour: the order remains in the user's orders and might be misleading.

![image.png](https://raw.githubusercontent.com/kailashgautham/ped/main/files/d8ad1b30-8aca-4045-a88a-9e93e20b64f1.png)

For this I'm not sure if it's a bug, I think it is intentional behaviour as the person can order an item before it is removed from the menu. But maybe something to make it more clear for users would be to ensure that after an item is deleted it is somehow indicated in the user's detailed view that they ordered something which now doesn't exist anymore. Do let me know if I misunderstood!

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kailashgautham/ped#5

**Comment by kokerinks** [comment]
repeated
