### ISSUE TITLE
[PE-D][Tester C] "Addmempts" command has a different error message than the expected one

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T13-4/tp#132]
Steps to reproduce:

1. Run the following command: `addmempts n/Irfan Ibrahim mp/999999999999999999999999999999999999999999`

Expected behaviour: that the program should inform me that the mp/ parameter value is too large.

Actual behaviour: as shown in the screenshot below. It says that input must be a valid integer although "999999999999999999999999999999999999999999" is technically a positive integer.

![image.png](https://raw.githubusercontent.com/kailashgautham/ped/main/files/a5cf648e-5772-4363-b990-d953426ea8ed.png)

My suggestion: the error for this can be changed to state that the expected maximum value is Java's definition of INT_MAX, or something along those lines.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kailashgautham/ped#8

**Comment by kokerinks** [comment]
REPEATED
