### ISSUE TITLE
[PE-D][Tester C] Name parameter does not allow S/o

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T13-4/tp#138]
Steps to reproduce:

1. Run the following command: `addmem n/Kailash S/o Tejas hp/1234 a/a e/kailash@test.com`

Expected behaviour: it allows the name with "S/o" (some Indians in Singapore have this as part of their official name).

Actual behaviour: it doesn't allow the name.

![image.png](https://raw.githubusercontent.com/kailashgautham/ped/main/files/1ad7b82e-b6ac-49f6-8689-464ca252ee32.png)

Although this isn't a bug, it would be cool if you could maybe switch the front slash in the prefixes to use "=" symbol instead to allow other special characters in the name!

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kailashgautham/ped#10

**Comment by kokerinks** [comment]
REPEAT
