### ISSUE TITLE
[PE-D][Tester C] Reward points has an integer overflow

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T13-4/tp#143]
Steps to reproduce:
1. Run the following command: `addpts n/Irfan Ibrahim p/2147483647`
2. Run the following command: `addpts n/Irfan Ibrahim p/1`

Expected behaviour: the program does not allow the user to increment points past a certain level.

Actual behaviour: the second command ceases to work and there is no output from the application, neither an error nor a success message.

![image.png](https://raw.githubusercontent.com/kailashgautham/ped/main/files/58eceb35-71f6-4c15-8ce9-1b13af2c9a49.png)

Suggestion: check if incrementing the value is going to go beyond the INT_MAX limits!

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kailashgautham/ped#12

**Comment by kokerinks** [comment]
set the max to 2,000,000,000 points for Reward Points and Membership Points
