### ISSUE TITLE
[PE-D][Tester C] Adding item with an invalid points per unit gives a wrong error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T13-4/tp#155]
Steps to reproduce:

1. Run the following command: `additem i/Bread p/aaaa`

Expected behaviour: an error message about how the point per unit is invalid.

Actual behaviour: an error that says it is an invalid command format.

![image.png](https://raw.githubusercontent.com/kailashgautham/ped/main/files/a77e04ab-afd9-44d1-9630-984b3fe2012d.png)

My suggestion: maybe you can modify the error handling here by checking for validity of each input when parsing the command!

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kailashgautham/ped#18

**Comment by kokerinks** [comment]
give up
