### ISSUE TITLE
Prepare release notes for V1.2 and upload the JAR file

### ISSUE THREAD

**Issue by billyhoce** [AY2324S2-CS2103T-T13-4/tp#46]
Write a fairly detailed Release Note in the text field GitHub provides for the description of the release. In particular, describe what has been changed (compared to AB3). This is just an itemized list of What's New -- no need to be as elaborate as a user guide.
Include screenshots (or screen recordings) of your product in action, featuring the changes you've done.

- [x] Release Notes
- [x] JAR file

**Comment by kokerinks** [comment]
Release created:
https://github.com/AY2324S2-CS2103T-T13-4/tp/releases/tag/v1.2
